# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattj_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='exp_type',
            field=models.CharField(choices=[('education', 'Education'), ('professional', 'Professional'), ('Project', 'project')], default='professional', max_length=50),
        ),
    ]
