# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattj_app', '0003_auto_20161201_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='exp_type',
            field=models.CharField(choices=[('education', 'Education'), ('professional', 'Professional'), ('Project', 'project')], default='professional', max_length=70),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
