# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattj_app', '0005_auto_20161201_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='employer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_type',
            field=models.CharField(choices=[('education', 'Education'), ('professional', 'Professional'), ('Project', 'project')], default='professional', max_length=30),
        ),
    ]
